# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b1b4cb90dd5aac00e61d60d337816f20a15563d333e8af3c356b57d767adf7da4a6420274ec2f5be58ec012bab44a384adeae53da071e7928bc7f71c98ca93c

test:
  secret_key_base: 73fc964a90fbddbfcffa2d3b57993beec2080965bc8da75a898dc0ef40cd3020d69c9946172a7ead9bc36f4fa0b97a508dc4187e7b22e95550bf971654fc79d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
